# Default values for syslog-ng.

replicaCount: 1

image:
  repository: balabit/syslog-ng
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.7.1"

# By default, https://github.com/syslog-ng/syslog-ng/blob/master/docker/syslog-ng.conf will be used that is part of the image
# You can ovverride this by providing your own config, for example:
# config: |
#   #############################################################################
#   # Default syslog-ng.conf file which collects all local logs into a
#   # single file called /var/log/messages tailored to container usage.
#   #
#   # The changes from the stock, default syslog-ng.conf file is that we've
#   # dropped the system() source that is not needed and that we enabled network
#   # connections using default-network-drivers(). Customize as needed and
#   # override using the -v option to docker, such as:
#   #
#   #  docker run ...  -v "$PWD/syslog-ng.conf":/etc/syslog-ng/syslog-ng.conf
#   #

#   @version: 4.7
#   @include "scl.conf"

#   source s_local {
#     internal();
#   };

#   source s_network {
#     default-network-drivers(
#       # NOTE: TLS support
#       #
#       # the default-network-drivers() source driver opens the TLS
#       # enabled ports as well, however without an actual key/cert
#       # pair they will not operate and syslog-ng would display a
#       # warning at startup.
#       #
#       #tls(key-file("/path/to/ssl-private-key") cert-file("/path/to/ssl-cert"))
#     );
#   };

#   destination d_local {
#     file("/var/log/messages");
#     file("/var/log/messages-kv.log" template("$ISODATE $HOST $(format-welf --scope all-nv-pairs)\n") frac-digits(3));
#   };

#   log {
#     source(s_local);
#     source(s_network);
#     destination(d_local);
#   };
config: ""

storage:
  enable: True
  storageClass: ""
  size: 500Gi
  
# Enable compressor to run a cron-job to compress files in /var/log/*-syslog older than retention_days
# it also delete the plain-text file in order to keep the folder size as low as possible.
# (if changes destination in server.config other than `/var/log/${YEAR}-${MONTH}-syslog` be aware you could breake this)
compressor:
  enabled: True
  #“At 04:25 on day 1 and 15, every month every year”
  schedule: "25 4 1,15 * *"
  retention_days: 120

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

# Syslog-ng manages its own capabilities as well, just make sure the two doesn't collide.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# syslog-ng have fixed ports tcp 601  and udp 514
service:
  type: ClusterIP
  # use externalip for a pre routede exter al ip.
  # TO-DO: LoadBalancer
  # type: externalip
  # externalIPs: 
  #   - 10.205.212.12

deployment: 
  resources: {}
  #   limits:
  #     cpu: 1000m
  #     memory: 256Mi
  #     ephemeral-storage: 2Gi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
